// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLReq) Reset() {
	*x = ShortenURLReq{}
	mi := &file_internal_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLReq) ProtoMessage() {}

func (x *ShortenURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLReq.ProtoReflect.Descriptor instead.
func (*ShortenURLReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURL      string                 `protobuf:"bytes,1,opt,name=shortURL,json=short_url,proto3" json:"shortURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResp) Reset() {
	*x = ShortenURLResp{}
	mi := &file_internal_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResp) ProtoMessage() {}

func (x *ShortenURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResp.ProtoReflect.Descriptor instead.
func (*ShortenURLResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResp) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type BatchShortenReq struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	BatchShortenData []*BatchShortenReq_BatchShorten `protobuf:"bytes,1,rep,name=batchShortenData,json=batch_shorten_data,proto3" json:"batchShortenData,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchShortenReq) Reset() {
	*x = BatchShortenReq{}
	mi := &file_internal_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenReq) ProtoMessage() {}

func (x *BatchShortenReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenReq.ProtoReflect.Descriptor instead.
func (*BatchShortenReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *BatchShortenReq) GetBatchShortenData() []*BatchShortenReq_BatchShorten {
	if x != nil {
		return x.BatchShortenData
	}
	return nil
}

type BatchShortenResp struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	BatchShortenData []*BatchShortenResp_BatchShorten `protobuf:"bytes,1,rep,name=batchShortenData,json=batch_shorten_data,proto3" json:"batchShortenData,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchShortenResp) Reset() {
	*x = BatchShortenResp{}
	mi := &file_internal_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenResp) ProtoMessage() {}

func (x *BatchShortenResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenResp.ProtoReflect.Descriptor instead.
func (*BatchShortenResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *BatchShortenResp) GetBatchShortenData() []*BatchShortenResp_BatchShorten {
	if x != nil {
		return x.BatchShortenData
	}
	return nil
}

type GetOriginalURLByShortReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURL      string                 `protobuf:"bytes,1,opt,name=shortURL,json=short_url,proto3" json:"shortURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLByShortReq) Reset() {
	*x = GetOriginalURLByShortReq{}
	mi := &file_internal_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLByShortReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLByShortReq) ProtoMessage() {}

func (x *GetOriginalURLByShortReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLByShortReq.ProtoReflect.Descriptor instead.
func (*GetOriginalURLByShortReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *GetOriginalURLByShortReq) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type GetOriginalURLByShortResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalURL   string                 `protobuf:"bytes,1,opt,name=originalURL,json=original_url,proto3" json:"originalURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLByShortResp) Reset() {
	*x = GetOriginalURLByShortResp{}
	mi := &file_internal_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLByShortResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLByShortResp) ProtoMessage() {}

func (x *GetOriginalURLByShortResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLByShortResp.ProtoReflect.Descriptor instead.
func (*GetOriginalURLByShortResp) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetOriginalURLByShortResp) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type BatchShortenReq_BatchShorten struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationID string                 `protobuf:"bytes,1,opt,name=correlationID,json=correlation_id,proto3" json:"correlationID,omitempty"`
	OriginalURL   string                 `protobuf:"bytes,2,opt,name=originalURL,json=original_url,proto3" json:"originalURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenReq_BatchShorten) Reset() {
	*x = BatchShortenReq_BatchShorten{}
	mi := &file_internal_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenReq_BatchShorten) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenReq_BatchShorten) ProtoMessage() {}

func (x *BatchShortenReq_BatchShorten) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenReq_BatchShorten.ProtoReflect.Descriptor instead.
func (*BatchShortenReq_BatchShorten) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BatchShortenReq_BatchShorten) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *BatchShortenReq_BatchShorten) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type BatchShortenResp_BatchShorten struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationID string                 `protobuf:"bytes,1,opt,name=correlationID,json=correlation_id,proto3" json:"correlationID,omitempty"`
	ShortURL      string                 `protobuf:"bytes,2,opt,name=shortURL,json=short_url,proto3" json:"shortURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenResp_BatchShorten) Reset() {
	*x = BatchShortenResp_BatchShorten{}
	mi := &file_internal_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenResp_BatchShorten) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenResp_BatchShorten) ProtoMessage() {}

func (x *BatchShortenResp_BatchShorten) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenResp_BatchShorten.ProtoReflect.Descriptor instead.
func (*BatchShortenResp_BatchShorten) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BatchShortenResp_BatchShorten) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *BatchShortenResp_BatchShorten) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

var File_internal_proto_shortener_proto protoreflect.FileDescriptor

const file_internal_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/shortener.proto\x12\x05proto\"!\n" +
	"\rShortenURLReq\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"-\n" +
	"\x0eShortenURLResp\x12\x1b\n" +
	"\bshortURL\x18\x01 \x01(\tR\tshort_url\"\xbe\x01\n" +
	"\x0fBatchShortenReq\x12Q\n" +
	"\x10batchShortenData\x18\x01 \x03(\v2#.proto.BatchShortenReq.BatchShortenR\x12batch_shorten_data\x1aX\n" +
	"\fBatchShorten\x12%\n" +
	"\rcorrelationID\x18\x01 \x01(\tR\x0ecorrelation_id\x12!\n" +
	"\voriginalURL\x18\x02 \x01(\tR\foriginal_url\"\xba\x01\n" +
	"\x10BatchShortenResp\x12R\n" +
	"\x10batchShortenData\x18\x01 \x03(\v2$.proto.BatchShortenResp.BatchShortenR\x12batch_shorten_data\x1aR\n" +
	"\fBatchShorten\x12%\n" +
	"\rcorrelationID\x18\x01 \x01(\tR\x0ecorrelation_id\x12\x1b\n" +
	"\bshortURL\x18\x02 \x01(\tR\tshort_url\"7\n" +
	"\x18GetOriginalURLByShortReq\x12\x1b\n" +
	"\bshortURL\x18\x01 \x01(\tR\tshort_url\">\n" +
	"\x19GetOriginalURLByShortResp\x12!\n" +
	"\voriginalURL\x18\x01 \x01(\tR\foriginal_url2\xe6\x01\n" +
	"\tShortener\x129\n" +
	"\n" +
	"ShortenURL\x12\x14.proto.ShortenURLReq\x1a\x15.proto.ShortenURLResp\x12B\n" +
	"\x0fBatchShortenURL\x12\x16.proto.BatchShortenReq\x1a\x17.proto.BatchShortenResp\x12Z\n" +
	"\x15GetOriginalURLByShort\x12\x1f.proto.GetOriginalURLByShortReq\x1a .proto.GetOriginalURLByShortRespB3Z1github.com/mp1947/ya-url-shortener/internal/protob\x06proto3"

var (
	file_internal_proto_shortener_proto_rawDescOnce sync.Once
	file_internal_proto_shortener_proto_rawDescData []byte
)

func file_internal_proto_shortener_proto_rawDescGZIP() []byte {
	file_internal_proto_shortener_proto_rawDescOnce.Do(func() {
		file_internal_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_shortener_proto_rawDesc), len(file_internal_proto_shortener_proto_rawDesc)))
	})
	return file_internal_proto_shortener_proto_rawDescData
}

var file_internal_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_shortener_proto_goTypes = []any{
	(*ShortenURLReq)(nil),                 // 0: proto.ShortenURLReq
	(*ShortenURLResp)(nil),                // 1: proto.ShortenURLResp
	(*BatchShortenReq)(nil),               // 2: proto.BatchShortenReq
	(*BatchShortenResp)(nil),              // 3: proto.BatchShortenResp
	(*GetOriginalURLByShortReq)(nil),      // 4: proto.GetOriginalURLByShortReq
	(*GetOriginalURLByShortResp)(nil),     // 5: proto.GetOriginalURLByShortResp
	(*BatchShortenReq_BatchShorten)(nil),  // 6: proto.BatchShortenReq.BatchShorten
	(*BatchShortenResp_BatchShorten)(nil), // 7: proto.BatchShortenResp.BatchShorten
}
var file_internal_proto_shortener_proto_depIdxs = []int32{
	6, // 0: proto.BatchShortenReq.batchShortenData:type_name -> proto.BatchShortenReq.BatchShorten
	7, // 1: proto.BatchShortenResp.batchShortenData:type_name -> proto.BatchShortenResp.BatchShorten
	0, // 2: proto.Shortener.ShortenURL:input_type -> proto.ShortenURLReq
	2, // 3: proto.Shortener.BatchShortenURL:input_type -> proto.BatchShortenReq
	4, // 4: proto.Shortener.GetOriginalURLByShort:input_type -> proto.GetOriginalURLByShortReq
	1, // 5: proto.Shortener.ShortenURL:output_type -> proto.ShortenURLResp
	3, // 6: proto.Shortener.BatchShortenURL:output_type -> proto.BatchShortenResp
	5, // 7: proto.Shortener.GetOriginalURLByShort:output_type -> proto.GetOriginalURLByShortResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_shortener_proto_init() }
func file_internal_proto_shortener_proto_init() {
	if File_internal_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_shortener_proto_rawDesc), len(file_internal_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_shortener_proto_goTypes,
		DependencyIndexes: file_internal_proto_shortener_proto_depIdxs,
		MessageInfos:      file_internal_proto_shortener_proto_msgTypes,
	}.Build()
	File_internal_proto_shortener_proto = out.File
	file_internal_proto_shortener_proto_goTypes = nil
	file_internal_proto_shortener_proto_depIdxs = nil
}
