---
apiVersion: v1
kind: Service
metadata:
  name: shortener
  namespace: ya-practicum
spec:
  selector:
    app: shortener
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
