name: BuildAndDeploy

on:
  pull_request:
  push:
    branches:
      - main
  
env:
  DEPLOYMENT_MANIFEST_PATH: |
      manifests/deployment.yaml
      manifests/service.yaml
  APP_PATH: ./cmd/shortener/main.go
jobs:
  build-and-deploy:
    runs-on: ya-url-shortener-ghr
    steps:
      - uses: azure/setup-kubectl@v4
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          username: ${{ vars.GCR_USERNAME }}
          password: ${{ secrets.GCR_CREDS }}
          registry: ${{ secrets.GCR_REPO }}
      - name: Set Up docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: ${{ vars.BUILDKIT_ENDPOINT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        id: docker-build
        with:
          push: true
          tags: ${{ secrets.GCR_REPO }}/${{ github.event.repository.name }}:${{ steps.short-sha.outputs.sha }}
          build-args: APP_PATH=${{ env.APP_PATH }}
      - uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - uses: Azure/k8s-deploy@v5
        with:
          namespace: ${{ vars.DEPLOY_NS }}
          annotate-resources: false
          annotate-namespace: true
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          images: ${{ secrets.GCR_REPO }}/${{ github.event.repository.name }}:${{ steps.short-sha.outputs.sha }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
